/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InvestirRouteImport } from './routes/investir'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EstimerRouteImport } from './routes/estimer'
import { Route as ConceptRouteImport } from './routes/concept'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as IndexRouteImport } from './routes/index'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestirRoute = InvestirRouteImport.update({
  id: '/investir',
  path: '/investir',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimerRoute = EstimerRouteImport.update({
  id: '/estimer',
  path: '/estimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptRoute = ConceptRouteImport.update({
  id: '/concept',
  path: '/concept',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/concept': typeof ConceptRoute
  '/estimer': typeof EstimerRoute
  '/faq': typeof FaqRoute
  '/investir': typeof InvestirRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/tarifs': typeof TarifsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/concept': typeof ConceptRoute
  '/estimer': typeof EstimerRoute
  '/faq': typeof FaqRoute
  '/investir': typeof InvestirRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/tarifs': typeof TarifsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/concept': typeof ConceptRoute
  '/estimer': typeof EstimerRoute
  '/faq': typeof FaqRoute
  '/investir': typeof InvestirRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/tarifs': typeof TarifsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/concept'
    | '/estimer'
    | '/faq'
    | '/investir'
    | '/mentions-legales'
    | '/qui-sommes-nous'
    | '/tarifs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/concept'
    | '/estimer'
    | '/faq'
    | '/investir'
    | '/mentions-legales'
    | '/qui-sommes-nous'
    | '/tarifs'
  id:
    | '__root__'
    | '/'
    | '/cgu'
    | '/concept'
    | '/estimer'
    | '/faq'
    | '/investir'
    | '/mentions-legales'
    | '/qui-sommes-nous'
    | '/tarifs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CguRoute: typeof CguRoute
  ConceptRoute: typeof ConceptRoute
  EstimerRoute: typeof EstimerRoute
  FaqRoute: typeof FaqRoute
  InvestirRoute: typeof InvestirRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investir': {
      id: '/investir'
      path: '/investir'
      fullPath: '/investir'
      preLoaderRoute: typeof InvestirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimer': {
      id: '/estimer'
      path: '/estimer'
      fullPath: '/estimer'
      preLoaderRoute: typeof EstimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept': {
      id: '/concept'
      path: '/concept'
      fullPath: '/concept'
      preLoaderRoute: typeof ConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CguRoute: CguRoute,
  ConceptRoute: ConceptRoute,
  EstimerRoute: EstimerRoute,
  FaqRoute: FaqRoute,
  InvestirRoute: InvestirRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
